spring.application.name=Market

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.servlet.context-path=/api
spring.web.error.include-message=always
logging.level.org.springframework.security=DEBUG

empresa.nombre=MarketPay
empresa.ruc=20XXXXXXXXXXX
empresa.direccion=Mercado Central Santa Rosa
empresa.telefono=999 999 999
empresa.logo.path=reports/assets/logo.png

# Ojo: cambia esta por una cadena fuerte, no la compartas en público
jwt.secret=mi-clave-super-secreta-para-firmar-tokens-123456
jwt.expiration-ms=1000000

# debug=true
# logging.level.org.springframework=DEBUG
