spring.application.name=Market

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.servlet.context-path=/api
spring.web.error.include-message=always
logging.level.org.springframework.security=DEBUG

# Ojo: cambia esta por una cadena fuerte, no la compartas en público
jwt.secret=mi-clave-super-secreta-para-firmar-tokens-123456
jwt.expiration-ms=86400000
